name: QBitUI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint_and_types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0

      - name: install
        run: yarn install
      
      - name: lint
        run: yarn lint

      - name: types
        run: yarn types